### ISSUE TITLE
Change scan name

### ISSUE THREAD

**Issue by Johnthe0n** [T0pCyber/hawk#104]
I have uninstalled and reinstalled the Hawk PS module and the scan is still showing with the same scan name from the previous install, is there a way to resolve this? 
Thank you

**Comment by clj575** [comment]
I can confirm this issue. This has been happening since the last update. The tenant would update when creating a new scan. Now it stays the same on every new client.

**Comment by T0pCyber** [comment]
We're taking a look. Appreciate letting us know.

**Comment by MSFT-SeanG** [comment]
@Johnthe0n & @clj575 

Which cmdlet are you calling that this is presenting the issue - User or Tenant investigations?

**Comment by MackT4** [comment]
@MSFT-SeanG I am seeing the same issue when using the **Start-HawkTenantInvestigation** cmdlet

**Comment by Johnthe0n** [comment]
Sorry, I have not logged in here in FOREVER. Its a new session I am running each time and I have uninstalled and reinstalled the HAWK system from PowerShell, that did not work. I am saving the sessions to different folders each time I run scans.

**Comment by jonnybottles** [comment]
Closing this ticket out as it appears to be the same issue identified in ticket https://github.com/T0pCyber/hawk/issues/106. Adding the original issue description to the comments of ticket 106.
