### ISSUE TITLE
Error entering haveibeenpwned.com apikey

### ISSUE THREAD

**Issue by sternyz** [T0pCyber/hawk#107]
**Describe the bug**
When entering my hibp api key the first time running Get-HawkUserPWNCheck, getting a 'Cannot index into a null array' error

**To Reproduce**
1. Get-HawkUserPWNCheck -user user@domain.com
2. prompted for the haveibeenpawned.com apikey: 
3. enter key
4. Cannot index into a null array error

**Expected behavior**
Key accepted, user email address run through Get-HawkUserPWNCheck

**Screenshots**
![2023-07-13_14-03-05](https://github.com/T0pCyber/hawk/assets/38505995/5f8e2b42-6220-4ee1-b00d-70bbacf1e157)

**Comment by MSFT-SeanG** [comment]
Reviewed this.

Please use the "-Email" switch, rather than "-User" when running the cmdlet. Null value is coming from lack of value in the Email field.

Noting this for further improvements & prompting for entry of the UPN, rather than only relying on switch.
