### ISSUE TITLE
Date/time error:  Cannot convert value "07/14/2023" to type "Microsoft.Exchange.ExchangeSystem.ExDateTime"

### ISSUE THREAD

**Issue by C-d-e-R** [T0pCyber/hawk#108]
When I run a user investigation, I am getting the following error:

```
Running Unified Audit Log Search
Search-UnifiedAuditLog -UserIDs username@domain.com -RecordType ExchangeItem -StartDate '04/14/2023' -EndDate '07/14/2023' -SessionCommand ReturnLargeSet -resultsize 5000 -sessionid 2103

Write-ErrorMessage : Cannot process argument transformation on parameter 'EndDate'. Cannot convert value "07/14/2023" to type "Microsoft.Exchange.ExchangeSystem.ExDateTime". Error: "String was not 
recognized as a valid DateTime."
```
**To Reproduce**
Run "Start-HawkUserInvestigation"
User the default date and search period
The error appears when running Get-HawkUserMailboxAuditing

![error](https://github.com/T0pCyber/hawk/assets/98779104/228dd6ae-310a-4cfb-b770-f15e5aa80749)

**Comment by T0pCyber** [comment]
Use todays date. That date is in the future.

**Comment by C-d-e-R** [comment]
Thanks, the error appears if you use the default values

![image](https://github.com/T0pCyber/hawk/assets/98779104/8917823d-fb5d-4b8f-9b0e-c38709315816)

and an earlier date:
![image](https://github.com/T0pCyber/hawk/assets/98779104/26f6eb16-f289-431b-90d4-f7fbd8caa2f7)

**Comment by T0pCyber** [comment]
What version are you running? The latest? I just tried version 3.1.0. 
Try running the search outside of Hawk. I can't repro it. 
Search-UnifiedAuditLog -UserIDs userprincipalid -RecordType ExchangeItem -StartDate '04/14/2023' -EndDate '07/14/2023'

**Comment by C-d-e-R** [comment]
Thanks I tried that and I get the same error...Its obviously a problem with my machine!

**Comment by T0pCyber** [comment]
@C-d-e-R  - Let us know if you encounter anything that you feel we need to clarify on the docs or technical checks. Any input is helpful to us. We're catching up on previous requests and will be getting to them in 3 weeks. :-)

**Comment by IvanKelleher** [comment]
I've had the same problem with a fresh W11 VM. I had no success playing around with culture value so I changed the display language to US and it now works fine.
