### ISSUE TITLE
Error running HAWK

### ISSUE THREAD

**Issue by alamanna993** [T0pCyber/hawk#115]
After Connecting to Azure AD and Exchange I run the Start-HawkTenantInvestigation command. I then get:

Start-HawkTenantInvestigation : The 'Start-HawkTenantInvestigation' command 
was found in the module 'HAWK', but the module could not be loaded. For more 
information, run 'Import-Module HAWK'.
At line:1 char:1
+ Start-HawkTenantInvestigation
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Start-HawkTenantInvestigation:S 
   tring) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
    
    
I then run Import-Module HAWK and get this error:

PS C:\WINDOWS\system32> Import-Module HAWK
Import-Module : Could not load file or assembly 'Azure.Core, Version=1.33.0.0, 
Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. 
The system cannot find the file specified.
At line:1 char:1
+ Import-Module HAWK
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundE 
   xception
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerS 
   hell.Commands.ImportModuleCommand

**Comment by NavyVet81** [comment]
I had this issue as well mine was giving a similar error on the AzureAD module. I had to uninstall EVERY version of Azure in powershell, then I uninstalled Hawk.

I reinstalled using the psresource command -force

**Comment by T0pCyber** [comment]
Closing. This ticket will be fixed with the modernization and bug fixes associated with using the MSGraph.
