### ISSUE TITLE
Hawk is not installing nor updating

### ISSUE THREAD

**Issue by beefgee862** [T0pCyber/hawk#122]
Hello,

I am trying to install hawk and I am getting the following error when installing or updating previous versions:

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PackageManagement\Install-Package : Unable to find dependent module(s) (RobustCloudCommand)
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RobustCloudCommand:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPack
   age

Please advise. Thanks

**Comment by arpsga** [comment]
The package has beend discontinued: https://www.powershellgallery.com/packages/RobustCloudCommand/2.1.0
You can still install it directly or manual.
