### ISSUE TITLE
Connect-MGGraph error after executing Start-HawkTenantInvestigation

### ISSUE THREAD

**Issue by blueteamcoffee** [T0pCyber/hawk#123]
**Describe the bug**

1. Manually installed

- `ExchangeOnlineManagement`
- `AzureAD`
- `Microsoft.Graph`

2. Successfully Connected to Azure via` Connect-AzureAD` 

3. Successfully connecte to EXO via `Connect-ExchangeOnline`

4. Started investigation via `Start-HawkTenantInvestigation`
--> error came up regarding Connect-MGGraph:

```
PS C:\temp> Start-HawkTenantInvestigation
Initializing Application Insights
Checking for latest version online
Found Version 3.1.0 Online
Latest Version Installed
Skipping Upgrade
Testing Graph Connection
Connecting to MGGraph using MGGraph Module
Connect-MGGraph : Could not load file or assembly 'file:///C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\3.5.0\netFramework\Azure.Core.dll' or one of its
dependencies. The system cannot find the file specified.
At line:30 char:9
+         Connect-MGGraph -Scopes "User.Read.All","Directory.Read.All"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MgGraph], FileNotFoundException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph

Select-MgProfile : The term 'Select-MgProfile' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:31 char:9
+         Select-MgProfile -Name "v1.0"
+         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Select-MgProfile:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Setting Up initial Hawk environment variable


        DISCLAIMER:
        [...]

        [...]

Do you agree with the above disclaimer?
[Y] Yes  [N] No  [?] Help (default is "Y"): y


Please provide an output directory: C:\temp\Hawk
Get-MGDomain : One or more errors occurred.
At line:81 char:9
+         [string]$TenantName = (Get-MGDomain | Where-Object {$_.isDefa ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgDomain_List], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Graph.PowerShell.Cmdlets.GetMgDomain_List

PS C:\temp>
```

**To Reproduce**
Repeat steps 1-4

**Expected behavior**
Since the error is about a missing file, providing a dependency or additional module installation tip would be usefull.

**Additional context**
Installed the modules not with` install-module`, but with `install-psresource`

**Comment by devallllll** [comment]
Could you update the instructions to using Microsoft.Graph?  - I am also really struggling with this and have a few questions 
Right now my solution is to remove and reinstall all the modules each time I want to use Hawk :(

**Comment by syne0** [comment]
HAWK only works with the below listed versions of the needed modules:
MSOnline 1.1.183.66 (yes it's deprecated, but HAWK still fails without it)
ExchangeOnlineManagement  3.4.0 (not sure if 3.5.0 works)
AzureAD 2.0.2.180
Microsoft.Graph 1.28.0 (not sure if 1.29.0 works)
RobustCloudCommand 2.1.0

If you require other versions of the above modules, then you'll need to import them as needed.

**Comment by blueteamcoffee** [comment]
Thx, I will try the next days and report!

**Comment by blueteamcoffee** [comment]
It works now, thanks.
Beneath the issue of the old(but right) versions there was also a client-side permissions-issue on my windows client.

**Comment by devallllll** [comment]
> It works now, thanks. Beneath the issue of the old(but right) versions there was also a client-side permissions-issue on my windows client.

I think this is why I had to uninstall and reinstall all the components - i'm still messing with a PS deployments script

**Comment by JPFish79** [comment]
![image](https://github.com/user-attachments/assets/806dd312-9c90-4a33-8c0b-b8fd6b602a0a)

I've verified I've got the correct versions installed.

But I keep getting the follow Warning/Errors:

![image](https://github.com/user-attachments/assets/388f60fa-3921-4d4d-bc26-e7b82b30c7c7)

Zoomed in on Errors:
![image](https://github.com/user-attachments/assets/b1d085e7-5e70-4651-85cc-63eed8c99c4a)
![image](https://github.com/user-attachments/assets/f009e690-813d-42bd-92c4-0e571029aa73)
![image](https://github.com/user-attachments/assets/f8f1a8ed-5d31-43ca-bce7-a4c5718adfad)

**Comment by syne0** [comment]
> ![image](https://private-user-images.githubusercontent.com/175449778/348392971-806dd312-9c90-4a33-8c0b-b8fd6b602a0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzA5MDgsIm5iZiI6MTcyMDkzMDYwOCwicGF0aCI6Ii8xNzU0NDk3NzgvMzQ4MzkyOTcxLTgwNmRkMzEyLTljOTAtNGEzMy04YzBiLWI4ZmQ2YjYwMmEwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNDE2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjJiM2E0MzU2MDdjOTU1Y2U1Y2RiOTcyZjgzOThlOWIzMjJkNzY5NzZhYmQ3YjQwODZmZjA3N2I2NDFiZTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.67JbmDzjQ23Ssb8vlZ7-0_TgVIn1_Y1ufHUorr5xYnQ)
> 
> I've verified I've got the correct versions installed.
> 
> But I keep getting the follow Warning/Errors:
> 
> ![image](https://private-user-images.githubusercontent.com/175449778/348393385-388f60fa-3921-4d4d-bc26-e7b82b30c7c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzA5MDgsIm5iZiI6MTcyMDkzMDYwOCwicGF0aCI6Ii8xNzU0NDk3NzgvMzQ4MzkzMzg1LTM4OGY2MGZhLTM5MjEtNGQ0ZC1iYzI2LWU3YjgyYjMwYzdjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNDE2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmNmOTIwOTU3YWNjZTViMWUxZTVlNWJmYTI4ZmRjN2M3NzA5M2E1NTBhZDY3ZTQ5MDMyYWZjYzY1MDAwNzA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x5RAy4GYtFxLclNsfdsaPwFXkAxIC_zvT5qSWNY8XEM)
> 
> Zoomed in on Errors: ![image](https://private-user-images.githubusercontent.com/175449778/348393556-b1d085e7-5e70-4651-85cc-63eed8c99c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzA5MDgsIm5iZiI6MTcyMDkzMDYwOCwicGF0aCI6Ii8xNzU0NDk3NzgvMzQ4MzkzNTU2LWIxZDA4NWU3LTVlNzAtNDY1MS04NWNjLTYzZWVkOGM5OWM0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNDE2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTYyNjgwYWNmMGU2NzcwYzk5NDY4NTQ1Y2YxYjMxYmVmMmVjZmZkMTRhN2I5YTA2MTNkODFjM2Y3MWQxYWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DT434SnWhN9w-W-21qtQYnPPWvk0p6SqYUFo8Fe7bTU) ![image](https://private-user-images.githubusercontent.com/175449778/348393602-f009e690-813d-42bd-92c4-0e571029aa73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzA5MDgsIm5iZiI6MTcyMDkzMDYwOCwicGF0aCI6Ii8xNzU0NDk3NzgvMzQ4MzkzNjAyLWYwMDllNjkwLTgxM2QtNDJiZC05MmM0LTBlNTcxMDI5YWE3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNDE2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjRlZjM0MzAzYzk4ZjRiZjlmZGU2ODM5YTk4MGI0YzhiYzE4MDQwYTVjN2VmNzhlYzMyMDViZmIyNGE3NGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cObM7jquJNdNLsMKsv9GSs7V4ZW9I0PuWyoXJZhY-Dg) ![image](https://private-user-images.githubusercontent.com/175449778/348393668-f8f1a8ed-5d31-43ca-bce7-a4c5718adfad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzA5MDgsIm5iZiI6MTcyMDkzMDYwOCwicGF0aCI6Ii8xNzU0NDk3NzgvMzQ4MzkzNjY4LWY4ZjFhOGVkLTVkMzEtNDNjYS1iY2U3LWE0YzU3MThhZGZhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNDE2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmNmODAyOTBkYzhmZDAwMmU2MzllMjRlMzA1YjBlY2Y1ZWVlMGZmMDE0ZWEyY2Y3MWNmNmI0YjFhNzYyOGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4b2QK_stfR2qSqkqs4wxyKcJaUAQ0BNJrTBEQfGF-Q0)

For the error with Select-MgProfile the way I've found to fix it reliably is to comment out that line in the Test_GraphConnection.ps1 function directly in the module's code. It was used for switching between beta graph and the 1.0 release.

Do you have more than 1 version of graph installed, such as the beta ones?

**Comment by JPFish79** [comment]
I only have the v1.28.0 Graph installed.  I'm still getting The Get-MGDomain error.

**Comment by T0pCyber** [comment]
> I only have the v1.28.0 Graph installed. I'm still getting The Get-MGDomain error.

Hi there, have you tried connecting to the Graph without using Hawk? Run Disconnect-MGraph and then reconnect with the scope "User.Read.All", "Directory.Read.All". I'm curious if you're having issues connecting. We do need to update the module and have that on the roadmap this summer.

**Comment by JPFish79** [comment]
Connect with no problems.
![Uploading Capture.PNG…]()

**Comment by jonnybottles** [comment]
We are consolidating this and other related issues under a new comprehensive ticket: [Modernize Authentication in Hawk to Replace AzureAD with Microsoft Graph](Modernize Authentication to Replace AzureAD with Microsoft Graph). This ticket addresses all outdated modules, cmdlets, and dependency problems, including Connect-MGGraph and Select-MgProfile. Please refer to the new ticket for updates and progress. Closing this issue as part of the modernization effort.
