### ISSUE TITLE
Fresh Install of Hawk (7/18/2024) on Fresh Win 10 or 11 won't run

### ISSUE THREAD

**Issue by Gray-0men** [T0pCyber/hawk#125]
After installing getting an error when running 
Start-HawkTenantInvestigation

Version 3.1.0

![image](https://github.com/user-attachments/assets/d0d9a6ff-a351-40e2-bca1-c3a0864c9000)

**Comment by Gray-0men** [comment]
Fixed my own issue as soon as I posted this. anyone getting this error 

Install-Module -Name ExchangeOnlineManagement -RequiredVersion 3.4.0

then go into 
C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement
and delete any newer version folder so that only 3.4.0 is there or just 
Uninstall-Module -Name ExchangeOnlineManagement -RequiredVersion <whatever version you have in that dir>


Looks like getting a fresh install of Hawk/Windows is:

```Set-ExecutionPolicy RemoteSigned
Install-Module -Name MSOnline -RequiredVersion 1.1.183.66
Install-Module -Name RobustCloudCommand -RequiredVersion 2.1.0
Install-Module -Name ExchangeOnlineManagement -RequiredVersion 3.4.0
Install-Module -Name Hawk
```

**Comment by IvanKelleher** [comment]
Small adjustment to this as RobustCloudCommand installs the latest version) of ExchangeOnlineManagement (currently 3.5.1). 

So:
```
Install-Module -Name MSOnline -RequiredVersion 1.1.183.66
Install-Module -Name ExchangeOnlineManagement -RequiredVersion 3.4.0
Install-Module -Name RobustCloudCommand -RequiredVersion 2.1.0
Install-Module -Name Hawk
```

**Comment by T0pCyber** [comment]
Robust Cloud command will removed as dependency and will build in capability to handle throttling into Hawk.
