### ISSUE TITLE
'Search-AdminAuditLog' cmdlet is now deprecated.

### ISSUE THREAD

**Issue by CorneliousJD** [T0pCyber/hawk#127]
Easily put -- 'Search-AdminAuditLog' cmdlet is now deprecated. and items are failing to run now because of it.

**Comment by Xandrov-tech** [comment]
I'm also having this issue and find Hawk to be super helpful when reviewing compromised email accounts. Are there any plans to resolve this by changing to use Search-UnifiedAuditLog instead? It'd be greatly appreciated

**Comment by T0pCyber** [comment]
We are working on updating the module. Sorry for the delay.

**Comment by jonnybottles** [comment]
To effectively manage and resolve this issue, we've broken it down into several smaller, more manageable tickets. Each ticket focuses on updating specific scripts within Hawk to replace the deprecated cmdlets with Search-UnifiedAuditLog or modern equivalents.

Here are the new tickets where we will be tracking the progress:

Ticket https://github.com/T0pCyber/hawk/issues/146: https://github.com/T0pCyber/hawk/issues/146
Ticket https://github.com/T0pCyber/hawk/issues/147: https://github.com/T0pCyber/hawk/issues/147
Ticket https://github.com/T0pCyber/hawk/issues/148: https://github.com/T0pCyber/hawk/issues/148
Ticket https://github.com/T0pCyber/hawk/issues/149: https://github.com/T0pCyber/hawk/issues/149
Ticket https://github.com/T0pCyber/hawk/issues/150: https://github.com/T0pCyber/hawk/issues/150
We will be closing this ticket (https://github.com/T0pCyber/hawk/issues/116) in favor of these new tickets. This approach allows us to focus on each script individually and ensure thorough testing and implementation.
