### ISSUE TITLE
Bug: Running Get-HawkTenantRBACChanges Error

### ISSUE THREAD

**Issue by oasec1** [T0pCyber/hawk#172]
### What happened?

Tried executing Start-HawkTenantInvestigation and gdo the follwing error. Did not have any issues authenticating. 

[12/8/2024 9:19:53 PM] - [ACTION] - Running Get-HawkTenantRBACChanges
[12/8/2024 9:19:54 PM] - [ACTION] - Gathering any changes to RBAC configuration

Write-ErrorMessage : A server side error has occurred because of which the operation could not be completed. Please try again after some time. If the problem still persists, please reach out to MS support.
At C:\Users\XSEEE\AppData\Local\Temp\tmpEXO_ebh5wx1e.brc\tmpEXO_ebh5wx1e.brc.psm1:1207 char:13
+             Write-ErrorMessage $ErrorObject
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-ErrorMessage

Then this error occurred.

Get-MgUser : A positional parameter cannot be found that accepts argument 'True'.
At C:\Program Files\WindowsPowerShell\Modules\HAWK\3.1.2\Hawk.psm1:3225 char:33
+     $users = foreach ($user in (Get-MGUser -All $True)){
+                                 ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-MgUser], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Get-MgUser

The script did finish.

Robert

### Steps to Reproduce

Execute Start-HawkTenantInvestigation

### Hawk Version

*** Version 3.1.2 ***

**Comment by jonnybottles** [comment]
Hello and thank you for using Hawk and reporting the bugs that you've encountered!

In terms of the `Get-HawkTenantRBACChanges.ps1`, this is already being tracked under the following ticket: [Bug: Update Get-HawkTenantRbacChanges.ps1 to Use Search-UnifiedAuditLog #146](https://github.com/T0pCyber/hawk/issues/146). We expect to have that bug fixed and resolved in a new release scheduled for shortly before or after the New Year.

For the `Get-MGUser` bug, we have just resolved this in our dev branch while making a complete migration from the AzureAD module to the MSGraph module. We have a little more testing to do on our end, but you should see a new release in the PowerShell gallery by the end of the week. This is all being tracked in the following ticket: [Bug: Modernize Authentication to Replace AzureAD with Microsoft Graph](https://github.com/T0pCyber/hawk/issues/162).

Given that the bugs you identified are being tracked in other tickets, we will be closing out this one for issue tracking efficiency purposes. Please feel free to follow the other tickets and thank you for using Hawk!
