### ISSUE TITLE
Parse JSON Data

### ISSUE THREAD

**Issue by dvdkea** [T0pCyber/hawk#25]
Is it possible to parse the JSON data in the Exchange_UAL_Audit_<user>.csv log file into seperate columns for ease of readability?

Thank you!!

**Comment by Absoblogginlutely** [comment]
I agree this would be useful - I've had to do this several times recently to make it easier to track down events on a certain folder.  Most recently I had someone saying that their sent items were being deleted and by expanding this information I was then easily able to filter on just sent items in the resulting csv file in excel.

**Comment by T0pCyber** [comment]
This will be fixed in next update. Sorry for taking so long.

**Comment by T0pCyber** [comment]
Updated in current release.
