### ISSUE TITLE
Consider moving all recorded times to UTC

### ISSUE THREAD

**Issue by Canthv0** [T0pCyber/hawk#26]

**Comment by Canthv0** [comment]
Currently times output for logging, and some outputs are in local time.

Should we identified these times and move them all to UTC so that everything can align time wise?
I believe that most of the outputs from logging are in UTC?

Looking for thoughts/feedback

**Comment by jamdunnDFW** [comment]
Yes.

**Comment by jamdunnDFW** [comment]
Forgive my brevity. But IMO any security related events should standardize to UTC. This would save people a ton of headaches.

**Comment by chingf0rd** [comment]
Yes - all in UTC makes much more sense.

**Comment by jonnybottles** [comment]
Closing out this ticket as multiple tickets referenced updating time in Hawk to be UTC. This ticket is now tracked under: https://github.com/T0pCyber/hawk/issues/151
