### ISSUE TITLE
Addition of Risk Events?

### ISSUE THREAD

**Issue by daga480** [T0pCyber/hawk#33]
Is it technically feasible for HAWK to pull RiskDetections such as those found in https://portal.azure.com/#blade/Microsoft_AAD_IAM/IdentityProtectionMenuBlade/RiskDetections, possibly through the Graph request below?  In environments that do not have UAL turned on, this is often the only historical logging of unauthorized sign-ins so it is of great value.

GET https://graph.microsoft.com/beta/riskDetections

**Comment by T0pCyber** [comment]
This will not be added to Hawk at this time. Using the Microsoft graph to pull these events is possible but NOT via Azure AD PowerShell. The use of the graph requires additional Azure AD Application configuration and certificate/credential implementation. This is a slightly more intrusive approach the original functionality of Hawk. We'll possibly look into enhancing Hawk in the future using the Microsoft Graph for those users who want a more permanent solution. Thanks for the suggestion.
