### ISSUE TITLE
Data collection information

### ISSUE THREAD

**Issue by mmascolino** [T0pCyber/hawk#35]
Thank you for the warning in the disclaimer that data is being collected.  Is it documented anywhere what data you are collected?  If not, would you consider doing that?

**Comment by cybermohr** [comment]
@mmascolino, thank you for reaching out about the data. Hawk provides many different PowerShell cmdlets that gather various different data. It is stated in the README that if you run Get-Help <cmdlet> -full, you can see the data that is gathered with that particular cmdlet. We are in the process populating another website that will detail much of what is being collected. Please checkout [https://cloudforensicator.com/](https://cloudforensicator.com/) . But keep in mind that it is currently under construction.
