### ISSUE TITLE
String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by Rzqu** [T0pCyber/hawk#36]
Hi,

Just started using HAWK to pull out all of the audit information on my 365 tenant but im coming across streams of errors relating to the date/time - i am running this within the UK, im not sure if this has any impact on your powershell code?

It then gets stuck in an infinite loop when searching a date range and carrying out various other tasks. It fails to pull anything from the audit files because of these errors.

![image](https://user-images.githubusercontent.com/39829605/79381513-0243bf80-7f5a-11ea-8ea4-cd174797ada0.png)

Any ideas?

Thanks.

**Comment by shannaniggans** [comment]
Same as issue #27
