### ISSUE TITLE
Module Detection - AzureAD/AzureADPreview

### ISSUE THREAD

**Issue by grandslamjmh** [T0pCyber/hawk#39]
It would be nice to install the Hawk Module if it could detect if you are already running Module: AzureAD or Module: AzureADPreview.

VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/HAWK/1.15.0'.
VERBOSE: Completed downloading 'HAWK'.
VERBOSE: Hash for package 'HAWK' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='HAWK', version='1.15.0',destination='C:\Users\Jordan\AppData\Local\Temp\2046577437'
VERBOSE: Validating the 'AzureAD' module contents under 'C:\Users\Jordan\AppData\Local\Temp\2046577437\AzureAD.2.0.2.16' path.
VERBOSE: Test-ModuleManifest successfully validated the module manifest file 'C:\Users\Jordan\AppData\Local\Temp\2046577437\AzureAD.2.0.2.16'.
VERBOSE: Validating the authenticode signature and publisher of the catalog file or module manifest file of the module 'AzureAD'.
VERBOSE: Catalog file 'AzureAD.cat' is not found in the contents of the module 'AzureAD' being installed.
VERBOSE: Valid authenticode signature found in the file 'AzureAD.psd1' for the module 'AzureAD'.
VERBOSE: Checking for possible command collisions for the module 'AzureAD' commands.
PackageManagement\Install-Package : The following commands are already available on this system:'Add-AzureADApplicationOwner 
**Shorten the list of all CmdLets**
,Set-AzureADUserPassword,Set-AzureADUserThumbnailPhoto,Update-AzureADSignedInUserPassword'. **This module 'AzureAD' may override the existing commands. If you still want to install this module 'AzureAD', use 
-AllowClobber parameter.**
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.3\PSModule.psm1:9685 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by grandslamjmh** [comment]
Duplicate of #11

**Comment by T0pCyber** [comment]
Duplicate. See Issue #11
