### ISSUE TITLE
Error on execution after installation module 'PSFramework' is not loaded

### ISSUE THREAD

**Issue by exente** [T0pCyber/hawk#56]
I tried to install and configure the Hack framework and after downloading and running the Powershell installation script, I got the following error messages, do you know what could be wrong?

PS C:\Windows\system32> **Start-HawkUserInvestigation**
Start-HawkUserInvestigation : The 'Start-HawkUserInvestigation' command was found in the module 'Hawk', but the module
could not be loaded. For more information, run 'Import-Module Hawk'.
At line:1 char:1
+ Start-HawkUserInvestigation
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Start-HawkUserInvestigation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\Windows\system32> **import-module hawk**
import-module : The required module 'PSFramework' is not loaded. Load the module or remove the module from
'RequiredModules' in the file 'C:\Program Files\WindowsPowerShell\Modules\hawk\2.0.0\hawk.psd1'.
At line:1 char:1
+ import-module hawk
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...2.0.0\hawk.psd1:String) [Import-Module], Missing
   MemberException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by T0pCyber** [comment]
Have you tried installing the module from the PowerShell Gallery? You will to install the module and all the dependencies. PSFramework is a dependency. 
 
Install-Module -Name Hawk

**Comment by exente** [comment]
I did it, but thanks to your advice I did the same with the other dependencies and it worked.

If someone has same issue you have to run following commands also to install all dependencies, after do it, you'll be able to run the scripts as designed:

Install-Module -Name PSFramework
Install-Module -Name PSAppInsights
Install-Module -Name CloudConnect
Install-Module -Name RobustCloudCommand

**Comment by LucasFerguson** [comment]
I also encountered these errors. After installing the dependencies manually and running the following commands I was able to Import the Hawk Module. I created this message just to help anyone in the future. I don't know why PSGallery is not automatically installing the dependencies.

Errors I received and how I fixed them.
`Import-Module : The required module 'ExchangeOnlineManagement' is not loaded.`
To fix: Import-Module ExchangeOnlineManagement
`Import-Module : The required module 'ExchangeOnlineManagement' with version '3.0.0' is not loaded.`
To fix: Update-Module -Name ExchangeOnlineManagement

`Import-Module : The required module 'AzureAD' is not loaded.`
To fix: Import-Module AzureAD
`Import-Module : The required module 'AzureAD' with version '2.0.2.140' is not loaded.`
To fix: Update-Module AzureAD

Thank you @T0pCyber and all contributors for creating this great toolset!

**Comment by gostlund** [comment]
I was having further issues with this due to it not being able to install the 'RobustCloudCommand' module, as the author apparently has unlisted the package: https://www.powershellgallery.com/packages/RobustCloudCommand/2.1.0

I was able to force the install by using the following command:
`Install-Module -Name RobustCloudCommand -RequiredVersion 2.1.0`
