### ISSUE TITLE
Get-HawkUserHiddenRule uses switch parameter for credential object

### ISSUE THREAD

**Issue by hjorslev** [T0pCyber/hawk#62]
**Describe the bug**
When reading the comment based help it seems that Get-HawkUserHiddenRule should take a credential object when using the -EWSCredential parameter:
`Get-HawkUserHiddenRule -UserPrincipalName user@contoso.com -EWSCredential (get-credential)`

However, -EWSCredential is currently a switch statement.

**To Reproduce**
Pass a credential object to the parameter -EWSCredential

**Expected behavior**
The parameter -EWSCredential should accept a credential object

**Comment by T0pCyber** [comment]
Will be updated on upcoming update.
