### ISSUE TITLE
Error when executing latest version of hawk: AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application

### ISSUE THREAD

**Issue by garilla2** [T0pCyber/hawk#67]
**Describe the bug**
On my recently deployed (1 month) windows 10 boxes, I get the following error when  Connecting to EXO using CloudConnect Module:

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application

**To Reproduce**
1. Execute Start-HawkTenanantInvestigation
2. Authenticate
2. Choose write directory
3. Choose date range from
4. Choose date range too
5. Error occurs and you are re-prompted to authenticate

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'a0c73c16-a7e3-4564-9a95-2bdf47383716'. 

**Expected behavior**
Expected the Hawk tenant investigation to execute as normal

**Additional context**
Tested on two fully patched windows 10 boxes, tested on multiple 365 tenants.

**Comment by T0pCyber** [comment]
This is potentially being caused by deprecation of legacy auth. Connect to Exchange-OnlineManagement using the V2 module before running the Tenant Investigation. In the process of removing CloudConnect and updating to Exchange Online V2 module dependency.
See below for updated V2 module 
https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps

**Comment by natv** [comment]
Having the same issue, have installed using command:

`Install-Module -Name ExchangeOnlineManagement -RequiredVersion 2.0.4`

This shows it's installed:

```
PS C:\WINDOWS\system32> Import-Module ExchangeOnlineManagement; Get-Module ExchangeOnlineManagement

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.4      ExchangeOnlineManagement            {Get-EXOCasMailbox, Get-EXOMailbox, Get-EXOMailboxFolderPermission, Get-EXOMailboxFolderStatistics...}
```

Same error:

Message:  AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'a0c73c16-a7e3-xxxx-xxxxxxxxxxxxxxxx'.

**Comment by T0pCyber** [comment]
Just pushed a tested and what seems to stable newer version of Hawk. There was a couple deprecated things that happened all at once. Let us know if you're still having issues. FYI, you'll be required to install AzureAD Module and will be promoted 3 times to connect to MSO, Azure and Exchange Online to complete the Start-HawkTenantInvestigation. Thanks for the heads up.

**Comment by natv** [comment]
confirmed, all working now thank you for the quick fix and for this tool!

**Comment by garilla2** [comment]
What amazing support, and what an amazing product. Everything working from my side on all installs, closing ticket.
