### ISSUE TITLE
Get-MailboxAuditLogsFiveDaysAtATime terminates prematurely

### ISSUE THREAD

**Issue by cfc-zcarter** [T0pCyber/hawk#78]
**Describe the bug**
Get-MailboxAuditLogsFiveDaysAtATime terminates prematurely if $StartDate and $EndDate are in different calendar years.   This is a result of $RangeEnd being declared as a string rather than a datetime, which forces an implicit type conversion of $EndDate to string in the comparison clause of the while loop, which in turn forces a lexical comparison of $RangeStart and $EndDate, which is incorrect.  In the US, for example, "12/31/2020" > "01/05/2021", which will cause an immediate termination of the while loop after the first execution of Search-MailboxAuditLog.

**File (please complete the following information):**
Get-HawkUserMailboxAuditing.ps1

**Comment by T0pCyber** [comment]
Updated in 3.0.0. Updated in Gallery.
