### ISSUE TITLE
Alter LoggingFolder name to append default tenant domain name

### ISSUE THREAD

**Issue by Snickasaurus** [T0pCyber/hawk#86]
Script to alter:
`HAWK\<version>\internal\functions\Initialize-HawkGlobalObject.ps1`

Line to alter:
81

The change:
Possible to add the following to get the default domain of the tenant to be used in the file name?

```
$TenantName = (Get-MsolDomain | Where-Object {$_.isDefault}).Name
$FileName = $TenantName.Substring(0, $TenantName.IndexOf('.'))
```

After change:
New directory name would look like

Hawk_contoso_20220227_1513

This would be super cool. This project is fantastic. Keep up the great work!

**Comment by T0pCyber** [comment]
Great idea! The team is updating Hawk. We'll add this in the next update. Appreciate the support.
