### ISSUE TITLE
Bad path for System.Net.IPNetwork.dll

### ISSUE THREAD

**Issue by ReedK-DFT** [T0pCyber/hawk#90]
**Describe the bug**
When doing a user investigation, getting the error:

Loading Networking functions from C:\Program Files\WindowsPowerShell\Modules\HAWK\3.0
.0\System.Net.IPNetwork.dll
Exception calling "LoadFile" with "1" argument(s): "The system cannot find the file specified. (Exception 
from HRESULT: 0x80070002)"
At line:38 char:9
+         [Reflection.Assembly]::LoadFile($dll)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

The file mentioned is actually at: C:\Program Files\WindowsPowerShell\Modules\HAWK\3.0
.0\Bin\

Copying the file from \Bin to \ removes the error.

**To Reproduce**
Run Start-HawkUserInvestigation -UserPrincipalName <username>

**Additional context**
I've uninstalled and reinstalled the module, but the issue persists

**Comment by T0pCyber** [comment]
Fixed in new 3.1.0 update.
