### ISSUE TITLE
Error Acquiring Token: System.Threading.ThreadStateException: ActiveX control

### ISSUE THREAD

**Issue by garyjblackwell** [T0pCyber/hawk#95]
**Describe the bug**

**To Reproduce**
1. Go to cmd and run Start-HawkTenantInvestigation

[2/8/2023 10:03:31 AM] - [ACTION] - Starting Tenant Sweep
[2/8/2023 10:03:31 AM] - [ACTION] - Running Get-HawkTenantConfiguration
[2/8/2023 10:03:31 AM] - Not Connected to Exchange Online
[2/8/2023 10:03:31 AM] - Connecting to EXO using CloudConnect Module
Error Acquiring Token:
System.Threading.ThreadStateException: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.
'
'
\netFramework\ExchangeOnlineManagement.psm1:750 char:21

**Comment by garyjblackwell** [comment]
I removed the newer version of ExchangeOnlineManagement and installed an older one, which appears to have resolved the issue.

**Comment by caseySmith94** [comment]
what is this, just for clarification

**Comment by garyjblackwell** [comment]
What is what?

**Comment by caseySmith94** [comment]
what you sent me. Is this regarding something I had applied for or?

**Comment by CTGNB** [comment]
***@***.***  &#128522;



Chris Armstrong


 [cid:coastlinetg_logo_400x200_54c7b942-53aa-41b7-a281-0cb9031820ab.png]
Office:
Email:
Web:    949.209.8752
***@***.******@***.***>
coastlinetechgroup.com<http://www.coastlinetechgroup.com>
Click <http://coastline.help/> <https://coastline.help> here<http://coastline.help> to visit our new customer portal.

**Comment by caseySmith94** [comment]
okay, good day.
